version: "3"

services: 
  nuxt:
    build: ./app/
    container_name: docker-nuxt-demo
    restart: always
    ports:
      -"3333.3333"
    command: 
      yarn run start
    
    nginx: 
      image: nginx:latest
      container_name: docker-nuxt-demo
      ports:
        -"80:80"
      volumes:
        - ./nginx:/etc/nginx/conf.d
      depends_on:
        -nuxt

